<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Index/Index/Index</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="/dist/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/dist/bootstrap/3.3.7/css/bootstrap-theme.min.css">
</head>
<body class="container">
Index/Index/Index<br />
<?php vd($session) ?>
<?php View::display('child', ['session' => $session]);?>

<script src="/dist/jquery/jquery-3.2.1.min.js"></script>
<script src="/dist/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>